### ISSUE TITLE
[Android Bootcamp] SMS Group Project

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#14]
cc @nesquena and @thecodepath

**Comment by vibhorB** [comment]
Good to see the list of issues you guys have come up with for Sprint 1.
- Good breakdown of tasks and 1st iteration should be achievable in the time frame.
- It is a good idea to get started on as many screens as possible to get v1 out, and then in later sprints you will have a lot of time to polish the UI and add more features once core functionality is done.
- As part of integration, everyone should keep playing with the app and testing all components and see how they fit together. Focus of transitions from one screen to other and the flow, but don't worry if all screens look different. Once you have the flow working quickly, you will have enough time to polish UI.
- Keep doing regular check-ins, updating issues and merging codes locally so that you don't face a lot of issues in working as a team. Doing this will give you better idea about the progress the team is making.

Good luck with the project and use your mentor as much as you can.
